version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@db:5432/$${POSTGRES_DB}
      JWT_SECRET: $${JWT_SECRET}
      SMTP_HOST: $${SMTP_HOST}
      SMTP_PORT: $${SMTP_PORT}
      SMTP_USER: $${SMTP_USER}
      SMTP_PASS: $${SMTP_PASS}
      CONTACT_EMAIL: $${CONTACT_EMAIL}
    depends_on:
      - db
    ports:
      - '5000:5000'
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '3000:80'
volumes:
  db-data:
