name: codex-app
services:
  - name: backend
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    environment_slug: node-js
    build_command: npm install
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
  - name: frontend
    source_dir: frontend
    dockerfile_path: frontend/Dockerfile
    environment_slug: node-js
    build_command: npm install && npm run build
    run_command: npm run preview
    envs:
      - key: VITE_API_URL
        value: http://localhost:3000
